### ISSUE TITLE
[Win] Error message at the first launch

### ISSUE THREAD

**Issue by yozhic** [c3er/mdview#3]
Every day when I start the mdview for the first time (from the command line with the path to the file), I get this error msg:
```js
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at stat (fs.js:828:10)
    at fs.stat (electron/js2c/asar.js:291:27)
    at Object.fs.stat (electron/js2c/asar.js:291:27)
    at Timeout._onTimeout (C:\totalcmd\Profile\utils\mdview\resources\app.asar\main.js:276:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
The second and subsequent launches are normal. I'm on the Windows 8.1 x64.

**Comment by c3er** [comment]
I could reproduce this error (though it didn't occur to me before).

**Comment by c3er** [comment]
I hope the new release 1.4.0 will fix this problem. I didn't manage to reproduce this error reliably, even following your steps. Fell free to reopen this issue, if you still encounter this error.
